### ISSUE TITLE
New project using the Sphinx MATLAB domain

### ISSUE THREAD

**Issue by denisrosset** [sphinx-contrib/matlabdomain#102]
The project is [RepLAB](https://github.com/replab/replab/) and the website, generated with Sphinx, is available here: https://replab.github.io/replab/

We wrote a little about the API generation process here https://replab.github.io/replab/blog/20200123-RepLAB-website-live.html , and some of the generated pages can be viewed in the "Technical Reference" header: https://replab.github.io/replab/api/print.html

Thanks a lot for this invaluable tool!

**Comment by joeced** [comment]
Thanks a lot for the kind works. 

When I have time, I'll add your project to the list.

**Comment by denisrosset** [comment]
See #107

**Comment by joeced** [comment]
Thanks for the contribution. My time for this project has been very limited.
