### ISSUE TITLE
Double quotes assignment before single quote argument in class method bug

### ISSUE THREAD

**Issue by H0R5E** [sphinx-contrib/matlabdomain#103]
Hi,

I've encountered a bug where the use of a double quotes string in an assigment command before using a single quote string as an argument, seems to cause a bug. It only happens if it's a class method. A minimal example (defined as part of package 'Package') is:

```
classdef Test
    
    methods
        
        function obj = raiseError(obj)
            errStr = "Hello World";
            error('ErrorID', errStr)
        end

    end
    
end
```

The output from sphinx is then something like:

```
WARNING: [sphinxcontrib-matlabdomain] Parsing failed in +Package.Test. Check if valid MATLAB code.
```

I installed into Anaconda through PyPi:

```
sphinxcontrib-matlabdomain 0.11.1                   pypi_0    pypi
```

**Comment by joeced** [comment]
Hi 

thanks for the report. I can confirm the error and is actively looking into it.
