### ISSUE TITLE
Could not import extension sphinxcontrib.matlab (exception: No module named 'sphinxcontrib.matlab')

### ISSUE THREAD

**Issue by TheScarfix** [sphinx-contrib/matlabdomain#106]
Trying to use this extension but get this error.

**Comment by joeced** [comment]
Can you elaborate a bit.
1) Did you install it with `pip install sphinxcontrib-matlabdomain`?
2) Did you add it in the `conf.py` file with `extensions = ['sphinxcontrib.matlab', 'sphinx.ext.autodoc']`

**Comment by TheScarfix** [comment]
```
extensions = [
    "sphinx_rtd_theme",
    "sphinxcontrib.matlab",
    "sphinx.ext.autodoc"
]
``` 
is what it looks like in my conf.py

`pip install -U sphinxcontrib-matlabdomain` was used to install

Python version is 3.8.3

**Comment by joeced** [comment]
Looks correct. Can you post a log text?

**Comment by TheScarfix** [comment]
log text of what?

**Comment by joeced** [comment]
Or console output of how you got the error.

**Comment by TheScarfix** [comment]
I tried running `./make html` and got this error.

```
Running Sphinx v2.1.0

Extension error:
Could not import extension sphinxcontrib.matlab (exception: No module named 'sphinxcontrib.matlab')
```

**Comment by joeced** [comment]
In a regular python interactive session, can you do `import sphinxcontrib.matlab`?

**Comment by TheScarfix** [comment]
yup that works

**Comment by joeced** [comment]
Can you create a minimal zip-file of your environment, i.e matlab sources and Sphinx files?

**Comment by TheScarfix** [comment]
I just tried it on my laptop and it works there so it must be something with my environment, think I'll just reinstall everything python related. thanks for your help though
