### ISSUE TITLE
Sphinx Version: 3.2.0 compatibility

### ISSUE THREAD

**Issue by kmruehl** [sphinx-contrib/matlabdomain#112]
There appears to be a compatibility issue with **Sphinx Version: 3.2.0 (Released: Aug 8, 2020)** and **sphinxcontrib-matlabdomain Version 0.11.2 (Released: May 18, 2020).** 

I am unable to compile MATLAB API documentation using sphinxcontrib-matlabdomain Version: 0.11.2 and Sphinx Version: 3.2.0 
- When I run Sphinx Version: 3.2.0 and remove  MATLAB API documentation this issue goes away
- When I revert to Sphinx Version: 3.1.1 and add MATLAB API documentation this issue goes away

Related to https://github.com/MHKiT-Software/MHKiT/issues/31

**Comment by joeced** [comment]
Sorry for not responding earlier. I have been too busy with other matters.

I can't reproduce the error though

**Comment by joeced** [comment]
Closing this, as I can't reproduce it locally.
