### ISSUE TITLE
Matlab and Python projects

### ISSUE THREAD

**Issue by FelixBiermann** [sphinx-contrib/matlabdomain#130]
Hello,

I am having problems with shared Matlab and Python projects. Basically, new Matlab scripts are only included if I set "primary_domain = 'mat" in conf.py, but then obviously no Python file is included in the html page. Without "primary_domain" set, only Python files are included. Do I need to manually add the Matlab entries into modules.rst/index.rst? 
I am aware, that this bug has been reported and was apparently solved, but I don't get it working...

In the hope, that it is possible, and I am just failing, that's how my project layout looks like: (For demonstration purpose, I am testing with test Matlab files from this repo)

├── base
│   ├── Domain.m
│   ├── MatlabClass.m
│   ├── Monoid.m
│   ├── NiceFiniteGroup.m
│   ├── PythonClass.py
└── docs
    ├── build
    ├── make.bat
    ├── Makefile
    └── source
        ├── conf.py
        ├── index.rst
        ├── modules.rst

**conf.py**:
sys.path.append(os.path.abspath('../..'))
matlab_src_dir = os.path.abspath('../..')
extensions = ['sphinxcontrib.matlab', 'sphinx.ext.autodoc', 'sphinx.ext.graphviz',
              'sphinx.ext.viewcode', "myst_parser", 'sphinx.ext.inheritance_diagram', 'sphinx.ext.autosectionlabel']
source_suffix = ['.rst', '.md']

Within docs/ I am using sphinx-apidoc (sphinx-apidoc -f -o source/ ../base)

Thanks a lot!

**Comment by joeced** [comment]
Hi

Would it be possible for you to attach a zip-file with the project? That would make it a lot easier for me to debug it?

**Comment by FelixBiermann** [comment]
Hi joeced,

Of course! A test project to reproduce this error is attached. I am using the latest versions of this repo (v0.12 and Sphinx (v4.4). 
Within the docs/ folder, I use the following commands to build the doc:

```console
sphinx-apidoc -f -o source/ ../base
make html 
```

The scripts are example scripts from this repo. 

Thank you for your work in general and for your help!

Regards,
Felix 

[Test_FB.zip](https://github.com/sphinx-contrib/matlabdomain/files/8405227/Test_FB.zip)

**Comment by FelixBiermann** [comment]
Hi joeced, 

thanks for the quick replies! 
So a solution for bigger, mixed projects would be to run apidoc once with and once without "primary_domain='mat'" and then combine the output files. Of course, some files will be overwritten by the second run and have to be moved somewhere else first, but than it is more of a copy&paste problem, which again could be automated. At least for my purposes.

Thanks for all your effort,
Felix

**Comment by joeced** [comment]
I guess that could work. I have never used `sphinx-apidoc` at work for any project, so I have very limited experience with it. Can I close the issue?
