### ISSUE TITLE
Problems linking methods (or functions)

### ISSUE THREAD

**Issue by cvergari** [sphinx-contrib/matlabdomain#131]
I am having a lot of trouble linking methods in a class (or functions, for that matters.

### My minimal class:

    classdef TestLinks < handle
        % TestLinks tests hyperlinks in the guide.
        % This is a link to a method :meth:`TestLinks.TestLinks.returnsX`.
        % 

        methods
            function x = returnsX(this)
		    % x = returnsX()
		    %
		    % This function always return 10
		    %
                    x = 10;
            end
        end
    end

### My index.rst:

    Welcome to TestLinks's documentation!
    ============================================

    .. mat:automodule:: TestLinks
    
    .. mat:autoclass:: TestLinks
        :members:	

### conf.py

It contains `sphinx.ext.autodoc` and `sphinx.ext.napoleon`, and I added my Matlab code path (which should work, since the class is correctly documented).

### This is the output:

![immagine](https://user-images.githubusercontent.com/19816908/161773715-c6397914-3ca5-4b5a-99eb-1dcdb79f45c1.png)

### What I expected:
In this output, `TestLinks.TestLinks.returnsX()` should be a hyperlink, but it is just bold text.

What am I doing wrong?

**Comment by joeced** [comment]
Can you show me the directory structure of the project or maybe a zip-file with the minimal project.

**Comment by cvergari** [comment]
Here is a zip file of the minimal example:
[TestLinks.zip](https://github.com/sphinx-contrib/matlabdomain/files/8421692/TestLinks.zip)

The directory structure is:

│TestLinks
├─TestLinks.m
├─docs_source
│  ├─make.bat
│  ├─Makefile
│  ├─source
│  │  ├─conf.py
│  │  ├─index.rst

Thanks!

**Comment by joeced** [comment]
You have not set the `primary_domain = 'mat'` in the `conf.py`.  So either do that, or change the reference to ``:mat:meth:`TestLinks.TestLinks.returnsX` ``.

```
classdef TestLinks < handle
    % TestLinks tests hyperlinks in the guide.
    % This is a link to a method :mat:meth:`TestLinks.TestLinks.returnsX`.
    % 

    methods
        function x = returnsX(this)
	    % x = returnsX()
	    %
	    % This function always return 10
	    %
                x = 10;
        end
    end
```

**Comment by cvergari** [comment]
That works! I guess I did not understand the domain definition, because in my actual class I was using `:mat::meth:`, with two colons to separate the domains...
Thank you!
