### ISSUE TITLE
Cannot use autodoc-skip-members with automodule?

### ISSUE THREAD

**Issue by edmondop** [sphinx-contrib/matlabdomain#141]
We expereince the following warnings:

```
WARNING: [sphinxcontrib-matlabdomain] Unexpected function name: "tests". Expected "myTest" in module "myProject.+myModule".
```

The MATLAB code is perfectly fine (it contains function-based unit tests) so we tried to exclude in this way the file from being processed:

```
def skip_MATLAB_tests(app, what, name, obj, skip, options):
    return name == "myTest"

def setup(app):
    app.connect('autodoc-skip-member', skip_MATLAB_tests)
```

but the autodoc-skip-member is not used, apparently, when the MATLAB package is processed

**Comment by joeced** [comment]
Hi

Can you provide are minimal example where you get this warning? Then it's easier for me to look into.

**Comment by joeced** [comment]
Hi again

Are you sure it's the MATLAB code is correct. It's warning you that a file is named `myTest`, but inside the file it's something like: `function tests(...)`.
