### ISSUE TITLE
autodoc functions that use inputParser?

### ISSUE THREAD

**Issue by Remi-Gau** [sphinx-contrib/matlabdomain#143]
just wondering if it would be possible to autogenerate the doc for functions that rely on [inputParser](https://nl.mathworks.com/help/matlab/ref/inputparser.html).

A bit like this extension does for python:
https://sphinx-argparse.readthedocs.io/en/stable/

To be clear I am not asking for a feature: I am just curious because it looks like one those things that would be a headache to implement.

**Comment by joeced** [comment]
Pretty much any thing is possible ;-), but I think this is out-of-scope for this extension.

**Comment by Remi-Gau** [comment]
Yup that's i thought too. 👍
