### ISSUE TITLE
Unable to document method with name `get`

### ISSUE THREAD

**Issue by BuildingAtom** [sphinx-contrib/matlabdomain#151]
I'm trying to use this to help write documentation for a class which has a method called `get` in it. Unfortunately, it doesn't seem like I'm able to actually get `autoclass` to generate any documentation output for this method.

A quick example is
```matlab
classdef ExampleGet < handle
    methods
        function varargout = get(self)
            % Gets the numbers 1-n and fills in the outputs with them
            %
            % Returns:
            %     double: multiple outputs with data `1` to `n` respectively.
            %
            for i=1:nargout
                varargout{i} = i;
            end
        end
    end
end
```

and the rst would have
```rst
.. mat:autoclass:: ExampleGet
   :show-inheritance:
   :members:
   :undoc-members:

```

but `get` would never be documented itself.

**Comment by joeced** [comment]
Thanks for the detailed report. I'll look into this soon
