### ISSUE TITLE
Add citation

### ISSUE THREAD

**Issue by mikofski** [sphinx-contrib/matlabdomain#164]
1. Use Zenodo
2. Add doi [![DOI](https://zenodo.org/badge/105161090.svg)](https://zenodo.org/badge/latestdoi/105161090)
3. Add [citation.ctf](https://github.com/citation-file-format/citation-file-format)

**Comment by joeced** [comment]
Looks good and thanks for still caring about the project :).
One question: Would rather have me as main author in PYPI. You are still listed and referred.

**Comment by mikofski** [comment]
It's amazing how this project just keeps going thanks to you! I was looking through the list of users and there are so many!

>Would rather have me as main author in PYPI. You are still listed and referred.

Yes, I think it's probably better. You can change `setup.py` to list yourself as the author:
https://github.com/sphinx-contrib/matlabdomain/blob/9102348811ef49aec64a9a0829ed5ec34130b855/setup.py#L17-L18

At this point you have authored more than I have. That would remove my email from the PyPI page so that you were the only reference as both author & maintainer. 

>Do I need to get a Zenodo account to change anything on the citation?

I think you probably should log in to https://zenodo.org using GitHub, and then I think you should automatically have access to https://zenodo.org/account/settings/github/repository/sphinx-contrib/matlabdomain. There's nothing to do to maintain the archive because the GitHub integrated webhook will create a new archive and DOI with each release. But in case anything goes wrong, it's probably best for you to have access.

I noticed that some docs are being deployed here: https://sphinxcontrib-matlabdomain.readthedocs.io/ is it worthwhile building this out and listing it on the GitHub page?
