### ISSUE TITLE
formatting of property defaults

### ISSUE THREAD

**Issue by rdzman** [sphinx-contrib/matlabdomain#175]
If `matlab_show_property_default_value` is set to `True`, a numerical default value is displayed in single quotes (e.g. `prop = '10'` and a char array default value is displayed in double quotes (e.g. `prop = "my_string_default"`). I haven't tried other types of values yet, but it seems to me that it makes more sense to display the default value directly as specified in the code.

Replacing these lines ...

https://github.com/sphinx-contrib/matlabdomain/blob/f9dcfef952294b48087bfb735f13c4bec260f934/sphinxcontrib/mat_documenters.py#L1035-L1037

... with ...

```python
    objrepr = self.object.default
```

... results in what I'm looking for, at least for these two simple examples. That is, I get `prop = 10` and `prop = 'my_string_default'`, respectively. However, I don't know what `sphinx.util.inspect.object_description()` does, so I'm not sure if this is a safe fix.

Oh, and to get it to work, this line ...
https://github.com/sphinx-contrib/matlabdomain/blob/f9dcfef952294b48087bfb735f13c4bec260f934/sphinxcontrib/mat_documenters.py#L1042

... also needs to be changed to ...
```python
    objrepr == None
```

Thoughts?

**Comment by joeced** [comment]
I briefly looked at this when implementing the `matlab_show_property_default_value` feature. It could definitely be simplified a lot. It looks like a left-over from the Python autodoc. We just want the string to displayed.

I started on this here: https://github.com/sphinx-contrib/matlabdomain/tree/property-default-value-rendering

I also tested the `test_docs` and setting the `matlab_show_property_default_value = True` in the `conf.py` file.

Given this input:

![image](https://user-images.githubusercontent.com/22655178/231677090-b9ac1324-9579-41a5-b076-712f191915d9.png)

Renders like this:

![image](https://user-images.githubusercontent.com/22655178/231677026-34d93176-c07d-4f01-847e-ee2376c8640f.png)

The strings are just printed verbatim, and the last one stripped the `...`. Any thoughts on how diligently we should try to clean up the property default value?

**Comment by joeced** [comment]
Excellent idea! I changed multiline default values (which are probably pretty rare in the wild) to just print the first and last part, joined with an ellipsis. Thus we achieve, single-line property default values.

![image](https://user-images.githubusercontent.com/22655178/232001842-014cdab6-c80d-4c4d-84f7-fcccba9554e5.png)

**Comment by joeced** [comment]
A PR is ready https://github.com/sphinx-contrib/matlabdomain/pull/176. Feel free to comment :)

**Comment by joeced** [comment]
Fixed in #176
