### ISSUE TITLE
Question about parseing scripts and using automodule.

### ISSUE THREAD

**Issue by changlichun** [sphinx-contrib/matlabdomain#202]
I am a newer to sphinx and matlabdomain.  I think this is a very useful and awesome extension. And I have a few questions while using.

* 1. I found that the documentation system only read the first comment line. I would like to know if it is possible to generate a document with a MATLAB `publish` like effect? [publishing-matlab-code](https://www.mathworks.com/help/matlab/matlab_prog/publishing-matlab-code.html)
* 2. How can I define the entries order when I using `automodule`
```
.. automodule:: <folder>
    :members:
```
* 3. Is it possible to automatically generate a separate page for each folder?

**Comment by changlichun** [comment]
And
* 4. How to specify the type of class properties in docstring?
``` matlab
classdef MyClass
    properties
        % matrix: description ...
        A;
        % string: ...
        s;
    end
end
```

**Comment by joeced** [comment]
Hi and welcome. 

1) there is no feature like *publish* or *live script*. That would require a running MATLAB version, which is not required at the moment.

2) the order can be controlled by: autodoc_member_order can be set to alphabetical, groupwise or bysource.

3) highly requested feature. But not possible at the moment. Definitely something to work on. 

4) MATLAB usually does show the type. In practice I personally use something like `% this is a :obj:`

5) I don't think so. We piggy-back on the Python autodoc feature, so there might be some feature there.  However,  I have never used that myself.

**Comment by changlichun** [comment]
Thank you very much for your message. It is really useful for me!
