### ISSUE TITLE
Error report: AttributeError: 'MatClass' object has no attribute 'path'

### ISSUE THREAD

**Issue by changlichun** [sphinx-contrib/matlabdomain#204]
I got such an error when I have a class named exactly same as the folder name. Although I can easily avoid it, I wonder if it can be fixed. 

My test file is attached.
[mytest.zip](https://github.com/sphinx-contrib/matlabdomain/files/11994752/mytest.zip)

**Comment by joeced** [comment]
Thanks for the report. I'm away from a computer at the moment, but will look into it ASAP.

**Comment by joeced** [comment]
Should be fixed in the latest release.
