### ISSUE TITLE
Feature request: show matlab class property dimensions, class, validators

### ISSUE THREAD

**Issue by luhuhis** [sphinx-contrib/matlabdomain#212]
In the spirit of #159, it would be nice to not only be able to show the default values, but also show property dimensions, class and validators. That is, simply print the line where the property is defined as is. This would make it much easier to document data structures. 
Maybe this is easy to do, since default value parsing already needs to atleast know something about the other attributes, since they have to be skipped as they are written between the variable name and default value.

Related matlab docs:
https://de.mathworks.com/help/matlab/matlab_oop/defining-properties.html

**Comment by joeced** [comment]
Thanks for the suggestion. Sounds like something that should be ok easy to add.
