### ISSUE TITLE
Unexpected parse warning

### ISSUE THREAD

**Issue by willem-pennings** [sphinx-contrib/matlabdomain#221]
I have a MATLAB class file which looks perfectly fine to me, but sphinx complains about it by throwing a warning:

`WARNING: [sphinxcontrib-matlabdomain] Parsing failed in Classes.@Test.Test. Check if valid MATLAB code.`

I have stripped down the contents of this class by trial and error (including the constructor) until I found the part it complains about, and this is the unmodified content of the remaining file:

```
classdef Test
    % Foo bar

    methods
        angle = GetAngle(obj);
        length = GetLength(obj);
    end
end
```

It has something to do with these two method definitions but I honestly do not know what...

**Comment by joeced** [comment]
Sorry for the late reply and thanks for the report.

I'll take a look at this very soon
