### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by kuykens** [sphinx-contrib/matlabdomain#55]
I have been attempting to install the extension but I encounter an error. See screenshot for error. Any pointers to solve it would be welcome. 

![sphinxmatlaberror](https://user-images.githubusercontent.com/15900353/34480663-ffb82870-efad-11e7-9b96-0cfdadf0d5f8.png)

**Comment by joeced** [comment]
Did you resolve the problem?

**Comment by kuykens** [comment]
Yes, I called PIP from (windows) command line. Remove the U and than it appeared to work OK. Still in learning phase and having quite some difficulties to get desired output.
