### ISSUE TITLE
automethod does not work with methods defined in class folders

### ISSUE THREAD

**Issue by joeced** [sphinx-contrib/matlabdomain#56]
For classes defined in class folders, `@ClassFolder`, methods defined in separate files in the folder need to use `autofunction`, rather than `automethod`. Further, the rendering is different.

For instance the `classMethod` must use `.. autofunction:: classMethod` and is rendered as 

    test_data.@ClassFolder.classMethod(obj, varargin)
    ...

Where the `method_inside_class` must use `.. automethod:: ClassFolder.method_inside_classdef` and is rendered as 
 
    ClassFolder.method_inside_classdef(a, b)
    ...

**Comment by mikofski** [comment]
bummer ☹️

**Comment by joeced** [comment]
@mikofski yeah :) ... I'll will look into it!

**Comment by sehyoun** [comment]
So this isn't a fundamental fix of this issue, but I have a workaround that I use for this case. The part that matter for me is the function/module signature. I usually try to get

some_name_I_want.function_name(var1,var2)

independent of the folder structure anyway. One can control this behavior by updating <add_directive_header> function of Documenter class of autodoc to introduce manual control of module, so I use

.. autofunction test_data.@ClassFolder.classMethod
    :module: some_name_I_want

I made the update in autodoc itself, but one could overload the <add_directive_header> in the documenter inherited in matlabdomain as well.

**Comment by mikofski** [comment]
Hi, so this was a hack I suppose rather than a big or a feature. In other words, I was aware of this issue when I added class folders. See the test docs for class folders [here](https://bwanamarko.alwaysdata.net/matlabdomain/#myclassfolder) they were rendered with the "@" symbol
