### ISSUE TITLE
Autodoc cannot work with both Python and Matlab code

### ISSUE THREAD

**Issue by joeced** [sphinx-contrib/matlabdomain#63]
From Twitter: https://twitter.com/ulizyh/status/966394096616165377

**Comment by joeced** [comment]
@mikofski Did Python and Matlab autodoc ever work together? I have been examining the latest Sphinx code (1.7.3), and it does not seem to take domain into account for instance, thus if you register a documenter with `objtype = 'function'` it will override the existing.

**Comment by mikofski** [comment]
Sorry. I don't know. When I used MATLAB with autodoc, I disabled the Python domain by making a _fake_ `std` domain because I didn't like how Sphinx produced two sets of indices (one for MATLAB and another for Python), so I never tried to generate both documents together. But then later on another user had an issue with the "fake" `std` domain, so I removed it in [v0.2.8](../releases/tag/0.2.8)

If you have questions on Sphinx development, maybe someone on the [Sphinx-dev](https://groups.google.com/forum/#!forum/sphinx-dev) mailing list can help?

**Comment by mikofski** [comment]
Also, without looking to carefully into this issue, so forgive my ignorance, but if you are documenting **two** sources then you probably should not set the `primary_domain` in `conf.py`, instead you must indicate which domain to use everywhere in your documentation. For example:

### mat doc rst

```
.. :mat:automodule: mymatfile
```

### py doc rst

```
.. :py:automodule: mypyfile
```

**Comment by joeced** [comment]
I just tried it, the `.. py:automodule::` and `.. mat:automodule` directives don't work. But I might have found another way, looking at https://github.com/erikrose/sphinx-js. He uses `add_directive_to_domain` to register the directive instead of `add_autodocumenter`. 

Thanks for your time and encouragement so far. I haven't had that much free time lately, but I'll see if I can put more hours in this project.

**Comment by mikofski** [comment]
Thanks to you this project is still alive! I really appreciate all the free time that you've already put in!

**Comment by masangster** [comment]
Hi guys, any updates on whether this is planned to be resolved, or if the current incompatibility will be simply left as-is?

**Comment by joeced** [comment]
@masangster  Funny  you are asking. I'm working on this feature right now, in this branch https://github.com/sphinx-contrib/matlabdomain/tree/autodirective. The only thing missing is wheter to have a common index for both python and matlab modules, or try to get separate. I can get the later generated, but haven't figured out how to link to it. 

So, if you can live with a common index, I can release a new version very soon. This will also have the advantage of not breaking current documentation sites if regenerated with a new version

**Comment by masangster** [comment]
@joeced great! Good timing! For my purposes I can definitely live with a common index for now (in some ways this is actually preferable), and agree it would be useful to not break existing sites. Looking forward to the new version! Any ETA by any chance?

**Comment by joeced** [comment]
Releasing a new version tonight. It will not have a common index, but a separate one for MATLAB modules.

**Comment by masangster** [comment]
Hi @joeced - thanks very much for this - it is working well now, however I have one small issue - the autoclass_content setting in conf.py doesn't seem to do anything now regardless of how I set it (ie class, init or both). Not sure if this was working before the latest updates or not as I didn't try it beforehand. Is there anything I am missing here? I tried using it together with .. autoclass:: and with .. automodule:: and neither work. Any suggestions?

**Comment by joeced** [comment]
I just tried, and it works for me™. The option controls how to print class and constructor docstrings.

Consider this MATLAB class:

```
classdef String
% Docstring for String

properties
    value
end

methods
    function obj = String(obj, args)
        % Docstring for String Constructor
        obj.value = args;
    end
end

end
```

With ``autoclass_content = 'init'``, it will print something like:

```
class matsrc.String(args)
   Docstring for String Constructor
```

With ``autoclass_content = 'both'``, it will print something like:

```
class matsrc.String(args)
   Docstring for String

   Docstring for String Constructor
```
