### ISSUE TITLE
Lists of return arguments like the inputs arguments.

### ISSUE THREAD

**Issue by dullin** [sphinx-contrib/matlabdomain#70]
MATLAB supports the return of multiple arguments but the sphinx doc by default only cares about 1 return argument.

Is it possible to have the same functionality for the return arguments as the input arguments have right now (be able to create a liste of arguments)?

**Comment by dullin** [comment]
As an added bonus, the function definition could have the outputs listed with the function name and parameters.

**Comment by joeced** [comment]
As you have noticed, return arguments are documented as a list of return values. Nothing hinders you from writing extended docstring documentation. I typically document MATLAB on conjuction with [Napoleon](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/), so I so no reason for adding these feature yet.

**Comment by ashkanpakzad** [comment]
Loving the ability to document my matlab project using sphinx, great library!

New to sphinx and running into this problem myself, using napoleon with google style docstrings. only work around I could I find was to do something like this for a function that returns varargout for example.

    % Returns:
    %   3 items
    %
    %   - **requiredarg** (:attr:`scalar`): desc
    %   - **optionalarg** (:attr:`vector`): desc
    %   - **optionalarg** (:attr:`vector`): desc

**Comment by joeced** [comment]
Usually I will just write a text message or as you do use a list. I don't think it is a big issue.
