### ISSUE TITLE
Sphinx Crashes when overloading builtin method in a class

### ISSUE THREAD

**Issue by sehyoun** [sphinx-contrib/matlabdomain#72]
When you overload a builtin method, e.g., sin, cos, isnan, in a class, the parser fails with error message 

```

Exception occurred:
  File "/path/lib/python2.7/site-packages/sphinxcontrib/mat_types.py", line 468, in __init__
    'modname: {}, name: {}'.format(modname, name))
TypeError: Object is not a function. Expected a function.modname: some.module.name, name: None

```

This is because in the MatlabLexer categorizes builtin functions as Token.Name.Builtin. One can fix this error by adding 

```
meth_tk[0] is Token.Name.Builtin or

``` 

on line 873 of mat_types.py file.

**Comment by sehyoun** [comment]
Let me try to make a minimal example (but occupied for a little bit right now, so it might take a little while).

**Comment by joeced** [comment]
I'll close it for now, please open a new issue if you can reproduce the error.
