### ISSUE TITLE
Nested functions not shown in output

### ISSUE THREAD

**Issue by kuykens** [sphinx-contrib/matlabdomain#74]
We are using nested functions as a more efficient approach to Matlab's classes. 
I noticed that these nested functions do not get listed in this tool's  output. It only picks up the main function name, that's it.

**Comment by joeced** [comment]
Can you elaborate a bit. A you talking about a package, class folder or something else. Could you show a minimal example?I'm

**Comment by kuykens** [comment]
Please see attached Sphinx project. The test_data2 folder contains a sample
nested function script.
The output of sphinx is the following screen shot snippet. The internal
method1 and method2 are not listed in the output.
We prefer the nested function OOP approach over the Matlab classes as it
appears to be more efficient in processing data.




2018-05-17 18:17 GMT+02:00 Jørgen Cederberg <notifications@github.com>:

**Comment by joeced** [comment]
Thanks, but I cannot see any attached documents?

**Comment by joeced** [comment]
I reread the issue and sorry to inform that this is not yet supported. If it were to be supported, it would only be [Local Functions](https://mathworks.com/help/matlab/matlab_prog/local-functions.html) as you can access the help string from MATLAB's help system.
