### ISSUE TITLE
autodoc_member_order = 'bysource' does not seem to work for matlab classes

### ISSUE THREAD

**Issue by RmStorm** [sphinx-contrib/matlabdomain#75]
I am creating documentation for a matlab program but the matlab-domain in combination with autodoc does not seem to support ordering the functions and properties of class 'bysource'. Is this a bug or simply not implemented?

**Comment by joeced** [comment]
That feature is not implemented, but could be a feature in the future.

**Comment by RmStorm** [comment]
Thank you for the quick reply, I will just order 'groupwise' than. Sadly I do not understand sphinx well enough to contribute.

**Comment by joeced** [comment]
According to http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autodoc_member_order, the ``autodoc_member_order`` can be set to ``group_wise`` or ``alphabetical``. Which order would you expect for ``group_wise``.

**Comment by joeced** [comment]
Fixed in 15e6ba93642c339ac9523f1fda3249283ae2692d
