### ISSUE TITLE
:undoc-members: option for .. autoclass:: directive does not seem to work

### ISSUE THREAD

**Issue by RmStorm** [sphinx-contrib/matlabdomain#76]
I try to add undocumented members like this:
.. autoclass::
	:members:
	:undoc-members:
but they do not show up in the compiled document. Except the first undocumented member. That one always shows up. Is this a bug? Or simply not implemented yet?

**Comment by joeced** [comment]
Works for me. You have to put the class name after `.. autoclass::`, like

```
.. autoclass:: MyClass
   :members:
   :undoc-members:
```
