### ISSUE TITLE
update link to Cantera in readme

### ISSUE THREAD

**Issue by mikofski** [sphinx-contrib/matlabdomain#77]
* the cantera link in users section of readme is broken
* also add opencobra link

**Comment by mikofski** [comment]
- closed in c8568fd039c470c522c1d0b5adf9dc5c26f55b19
- @joeced I hope it's okay, I just made this change directly in master since it was so tiny :)

**Comment by joeced** [comment]
@mikofski  Thanks - perfectly okay.
