### ISSUE TITLE
ENH: conda build

### ISSUE THREAD

**Issue by mikofski** [sphinx-contrib/matlabdomain#78]
Release matlabdomain on [conda-forge](https://conda-forge.org/docs/)?

**Comment by SergioCordova** [comment]
Hello,

Having a conda-forge release will be very helpful to my team. Is this something that could be done in the near future?

**Comment by joeced** [comment]
Prepared a PR at https://github.com/conda-forge/staged-recipes/pull/23966

**Comment by joeced** [comment]
Added to the conda-forge feedstock: https://github.com/conda-forge/sphinxcontrib-matlabdomain-feedstock
