### ISSUE TITLE
enumerations and events cause premature end of m-file parsing

### ISSUE THREAD

**Issue by goszpeti** [sphinx-contrib/matlabdomain#79]
If an m-file class contains enumerations and events, the file parsing will end at that declaration. 
example code:

```
class myclass

enumeration 
MYENUM
end

function myfunc()
end
end
```

myfunc() will not be parsed.
I already found the culprit for this in mat_types.py at lines 964 and 974 (version 0.34).
idx is not increased after exiting the while loop, so the next end will be considered as the class definitions end.

**Comment by joeced** [comment]
Thanks for the detailed report, it was very easy to find the error. 

Fixed in version 0.3.5 (#4b61919ff44fd6508e1d153ba4586c964d7a1e6b)
