### ISSUE TITLE
.. autoclass:: failing if a method uses a string with "%"

### ISSUE THREAD

**Issue by ludovicsteinbach** [sphinx-contrib/matlabdomain#87]
It seems that .. autoclass:: fails to document a class if one of the method uses sprintf and a formatSpec that includes a '%' character.

**Class definition**
```
classdef whatever
    %WHATEVER Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        Property1
    end
    
    methods
        function obj = whatever(inputArg1)
            %WHATEVER Construct an instance of this class
            %   Detailed explanation goes here
            obj.Property1 = sprintf("%d",inputArg1);
        end
        
        function outputArg = method1(obj,inputArg)
            %METHOD1 Summary of this method goes here
            %   Detailed explanation goes here
            outputArg = obj.Property1 + inputArg;
        end
    end
end
```

**rst**
`.. autoclass:: whatever`

**Error**
[sphinx-err-w_6f0dvv.log](https://github.com/sphinx-contrib/matlabdomain/files/2822636/sphinx-err-w_6f0dvv.log)

**Comment by joeced** [comment]
I tried running this on my own machine, where it doesn't fail. Can you provide a list with version numbers of installed modules, something like `pip list`.

**Comment by joeced** [comment]
Fixed in https://github.com/sphinx-contrib/matlabdomain/commit/abb5c34f44399a87f35447818aca2cd3173667d4. 

I just pushed an update, fixing the parsing of strings in double quotes. I'll prepare a new release tonight.
