### ISSUE TITLE
Package links

### ISSUE THREAD

**Issue by denisrosset** [sphinx-contrib/matlabdomain#93]
Hi,
first, thanks for this fantastic piece of software; it's great to produce API documentation in a mostly sane manner.

I deduced that package references should include the prefix `+`, so that for example, I'll be `.. automodule:: +replab` to document the `replab` package. However, when classes in the `replab` package inherit other classes in the same package, the automatic super class reference (`:show-inheritance:`) will be produced without the `+`, so the hyperlink is not present.

Am I doing something wrong?

(our project is here https://github.com/replab/replab and I'm in the process of migrating the documentation)

**Comment by joeced** [comment]
Hi, thanks for the kind words.

I just tried it out on your repo (and thanks for providing that, it makes it so much easier to debug), and I see the same issue. I will look further into this.

**Comment by denisrosset** [comment]
Thanks @joeced! I'm still wiggling things around with Sphinx, as Python is not an ecosystem I know well.

Right now, our website is still published by a mix of Jekyll and Matlab `publish`+postprocessing.

In the future, I hope that RepLAB can serve as an example of a mid-size project that demonstrates the `matlabdomain` capabilities.

**Comment by joeced** [comment]
So I looked at it closer now, and it requires a bit of work to fix. The reason for it not working now, is that the usual behavior is to have a _src_ folder, which acts as the _module_ (which is taken from Python concepts). When you add the module not all classes and functions have been parsed, and thus it does know `replab.Str`.

The better behavior would be to scan the entire `matlab_src_dir`for MATLAB packages and files. This is related to issue #81. 

As this is probably the biggest nuisance with `matlabdomain`, I'll start working on a solution.
