### ISSUE TITLE
Does the `inherited-members` autodoc option works with the Matlab domain?

### ISSUE THREAD

**Issue by denisrosset** [sphinx-contrib/matlabdomain#98]
Hi,
still working on the Sphinx integration in RepLAB. Thanks for the work on links for the base classes, now they work!

Adding the `inherited-members` option to autodoc seems to produce an empty list of methods in the documentation. Is this something that is expected to work, or should I find a workaround?

Best,
Denis

**Comment by joeced** [comment]
No, I just tried it. It has not been implemented and I have never used it. 

If it's something you really need, you could try and implement it :)

**Comment by denisrosset** [comment]
Ok thanks! Would you mind if I submit a PR to update the documentation in that respect?

**Comment by joeced** [comment]
You are welcome to contribute, but where does the documentation mention `inherited-members`?

**Comment by denisrosset** [comment]
You're right, it doesn't! We ended up adding some preprocessing to our source code to include the inheritance information; it's not online yet, but we'll publish it soon -- I think `matlabdomain` is a really nice piece of code, but indeed, adding `inherited-members` opens a whole can of worms.

**Comment by denisrosset** [comment]
(If you wish to close that issue, I'm totally on board. I realize how non-trivial making all these things work is, and what the impedance mismatch between Matlab and Sphinx is)
